import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]


[window.padding]
x = 25
y = 20

[window]
# dimensions = { columns = 120, lines = 30 }
# padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "Buttonless"
# startup_mode = "Maximized"
opacity = 0.95
option_as_alt = "OnlyLeft"

[env]
TERM = "xterm-256color"

[font]
size = 20.0

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001bOH"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001bOF"
